version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes:
       - ./:/var/www
    ports:
          - "8080:80"
    depends_on:
         - app
